# ##############################################################################
# VCPKG Path Validation
# ##############################################################################

if(NOT DEFINED VCPKG_ROOT_ENV AND DEFINED ENV{VCPKG_ROOT_ENV})
    set(VCPKG_ROOT_ENV "$ENV{VCPKG_ROOT_ENV}")
endif()

# Status icons/strings
set(CHECK_OK "[OK]")
set(CHECK_FAIL "[FAILED]")
set(CHECK_WARN "[WARN]")

# 1. Check DROGON_CTL_COMMAND
if(DEFINED DROGON_CTL_COMMAND)
    if(NOT EXISTS "${DROGON_CTL_COMMAND}")
        set(STATUS_DROGON "${CHECK_FAIL}")
        message(WARNING "DROGON_CTL_COMMAND is set to: ${DROGON_CTL_COMMAND}")
        message(WARNING "But this path does NOT exist!")
        message(WARNING "Please check your vcpkg installation and triplets.")
        message(WARNING "Expected location: ${DROGON_CTL_COMMAND}")
        message(WARNING "")
        message(WARNING "To fix:")
        message(WARNING "  1. Install drogon with correct triplet:")
        message(WARNING "     ./vcpkg install drogon --triplet x64-linux")
        message(WARNING "  2. Or set DROGON_CTL_COMMAND explicitly in your preset")
        message(FATAL_ERROR "DROGON_CTL_COMMAND not found!")
    else()
        set(STATUS_DROGON "${CHECK_OK}")
        message(STATUS "Found DROGON_CTL_COMMAND: ${DROGON_CTL_COMMAND}")
    endif()
else()
    set(STATUS_DROGON "${CHECK_FAIL}")
    message(WARNING "DROGON_CTL_COMMAND is NOT set!")
    message(WARNING "This will cause drogon_create_views to fail.")
    message(WARNING "Please add to your CMake preset:")
    message(WARNING "  \"DROGON_CTL_COMMAND\": \"\${env:VCPKG_ROOT_ENV}/installed/x64-linux/tools/drogon/drogon_ctl\"")
    message(FATAL_ERROR "DROGON_CTL_COMMAND is required!")
endif()

# 2. Check CMAKE_TOOLCHAIN_FILE
if(DEFINED CMAKE_TOOLCHAIN_FILE)
    if(NOT EXISTS "${CMAKE_TOOLCHAIN_FILE}")
        set(STATUS_TOOLCHAIN "${CHECK_FAIL}")
        message(WARNING "CMAKE_TOOLCHAIN_FILE is set to: ${CMAKE_TOOLCHAIN_FILE}")
        message(WARNING "But this path does NOT exist!")
        message(WARNING "Please check your vcpkg installation path.")
        message(FATAL_ERROR "CMAKE_TOOLCHAIN_FILE not found!")
    else()
        set(STATUS_TOOLCHAIN "${CHECK_OK}")
        message(STATUS "Using vcpkg toolchain: ${CMAKE_TOOLCHAIN_FILE}")
    endif()
else()
    set(STATUS_TOOLCHAIN "${CHECK_WARN}")
    message(WARNING "CMAKE_TOOLCHAIN_FILE is NOT set!")
    message(WARNING "vcpkg integration may not work correctly.")
    message(WARNING "Please add to your CMake preset:")
    message(WARNING "  \"CMAKE_TOOLCHAIN_FILE\": \"\${env:VCPKG_ROOT_ENV}/scripts/buildsystems/vcpkg.cmake\"")
endif()

# 3. Check vcpkg triplet setting
if(DEFINED VCPKG_TARGET_TRIPLET)
    set(STATUS_TRIPLET "${CHECK_OK}")
    message(STATUS "vcpkg triplet: ${VCPKG_TARGET_TRIPLET}")
else()
    set(STATUS_TRIPLET "${CHECK_WARN}")
    message(STATUS "VCPKG_TARGET_TRIPLET not set, using default")
endif()

# 4. Check for vcpkg installed packages
set(STATUS_INSTALLED "${CHECK_FAIL}")
if(DEFINED VCPKG_ROOT_ENV)
    set(VCPKG_INSTALLED_DIR "${VCPKG_ROOT_ENV}/installed")
    if(EXISTS "${VCPKG_INSTALLED_DIR}")
        set(STATUS_INSTALLED "${CHECK_OK}")
        message(STATUS "vcpkg installed packages directory: ${VCPKG_INSTALLED_DIR}")
        
        if(DEFINED VCPKG_TARGET_TRIPLET)
            set(TRIPLET_DIR "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
            if(EXISTS "${TRIPLET_DIR}")
                message(STATUS "Found triplet directory: ${TRIPLET_DIR}")
            else()
                set(STATUS_INSTALLED "${CHECK_WARN}")
                message(WARNING "Triplet directory not found: ${TRIPLET_DIR}")
                message(WARNING "You may need to install packages for this triplet:")
                message(WARNING "  ./vcpkg install drogon fmt jsoncpp --triplet ${VCPKG_TARGET_TRIPLET}")
            endif()
        endif()
    endif()
endif()

# ##############################################################################
# Validation Summary (Rangkuman)
# ##############################################################################
message(STATUS "-----------------------------------------------------------")
message(STATUS " VCPKG & DROGON CONFIGURATION SUMMARY")
message(STATUS "-----------------------------------------------------------")
message(STATUS " ${STATUS_TOOLCHAIN} CMAKE_TOOLCHAIN_FILE")
message(STATUS " ${STATUS_DROGON} DROGON_CTL_COMMAND")
message(STATUS " ${STATUS_TRIPLET} VCPKG_TARGET_TRIPLET")
message(STATUS " ${STATUS_INSTALLED} VCPKG_INSTALLED_DIR")
message(STATUS "-----------------------------------------------------------")
message(STATUS "")